### ISSUE TITLE
multiline cft?

### ISSUE THREAD

**Issue by niksite** [chrislemke/ChatFred#24]
I had a look at the [troubleshooting section](https://github.com/chrislemke/ChatFred#troubleshooting-%EF%B8%8F)
- [x] Yes
- [ ] No

**Describe the bug**

Sometimes I ask `cft` a question with would require a multiline answer but all I get is a single line.

**To Reproduce**
1. `cft how to clean yum cache?`
2. Getting `To clean yum cache, run the following command:` which clearly misses the command.

**Expected behavior**
```
To clean yum cache, run the following command: sudo yum clean all
```

**Comment by niksite** [comment]
If we want only single line answers, please update the default prompt for InstructGPT to something like `Please answer in single line` (or make a config entry for that?).

**Comment by chrislemke** [comment]
Hey @niksite!
Thanks for reporting this! I have to admit I have not worked on the InstructGPT for quite a while. Is there a specific reason you are using `cft` and not `cf`? Anyhow I will investigate this issue and come back to you!

**Comment by niksite** [comment]
I prefer CFT because it is so much faster

**Comment by chrislemke** [comment]
Good point.

I think the problem is connected to those two lines:
- https://github.com/chrislemke/ChatFred/blob/main/workflow/src/text_completion.py#L34
- https://github.com/chrislemke/ChatFred/blob/main/workflow/src/text_completion.py#L108

To run InstructGPT as some kind of ChatBot for answering questions it needs to be implemented in a certain way ([read more](https://platform.openai.com/docs/guides/completion/factual-responses)). 

In the `prompt_from_query` function we prepare the request for the model:

```
def prompt_from_query(query: str) -> str:
    """Creates a suitable prompt for the OpenAI API."""
    return f"Q: {query}\nA:"
``` 
in line 108 we tell the model to end at every new line `\n`. 

```
stop=["\n", "<|endoftext|>"],
```

I guess that is the reason for the problem.

**Comment by chrislemke** [comment]
I fixed the issue. You can test it in [this beta version](https://github.com/chrislemke/ChatFred/releases/tag/v1.3.0-dev4).
